name: Docker Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v3
        with:
          context: roles/openvpn/files
          file: roles/openvpn/files/Dockerfile
          cache-to: ghcr.io/letheanvpn/ansible-openvpn
          cache-from: ghcr.io/letheanvpn/ansible-openvpn
          push: true
          tags: lthn/openvpn,ghcr.io/letheanvpn/ansible-openvpn
      - name: Docker Build
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          cache-to: ghcr.io/letheanvpn/ansible-openvpn
          cache-from: ghcr.io/letheanvpn/ansible-openvpn
          push: false
          tags: lthn/openvpn,ghcr.io/letheanvpn/ansible-openvpn
